### ISSUE TITLE
Please add RSS feed

### ISSUE THREAD

**Issue by a13xp0p0v** [stffrdhrn/stffrdhrn.github.io#4]
Hello @stffrdhrn 

Your blog is really great, thanks!

Could you please add the RSS feed?
Howto:
https://dzhavat.github.io/2020/01/19/adding-an-rss-feed-to-github-pages.html

Thanks!

**Comment by stffrdhrn** [comment]
Thanks, this has been on my todo list for the last few months.  Btw which RSS reader do you use?

I will try to do today.

**Comment by stffrdhrn** [comment]
It should be here now:

https://stffrdhrn.github.io/feed.xml

**Comment by a13xp0p0v** [comment]
Thank you!
(I use Liferea reader)
